### ISSUE TITLE
Design our product section

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/enersun-web#11]
- [x] design product list display
- [x] design pop-up to display product description

Display the following fields:
- product image
- product name
- product category
- simple description
- price
![image](https://user-images.githubusercontent.com/30463117/186099352-f76a7339-d9c1-471e-ba4a-3fb3c150f4e1.png)
![image](https://user-images.githubusercontent.com/30463117/186099491-cccf0a0d-f23c-4b82-81e7-ad596f02c863.png)

**Comment by russel0907** [comment]
## Our Product section
![Enersun-—-Save-Energy-Save-Earth-Love-All-Serve-All](https://user-images.githubusercontent.com/94702093/186335430-27630474-45fe-441a-b8c5-70368b285a4a.png)


## Pop-up product detail design
![Enersun-—-Save-Energy-Save-Earth-Love-All-Serve-All model](https://user-images.githubusercontent.com/94702093/186335518-827fe5b3-670f-40d4-bfcc-f66232fe79c9.png)
