### ISSUE TITLE
Display popup when product is clicked

### ISSUE THREAD

**Issue by paragasu** [phisoft/enersun-web#21]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/27353/188361215-f7dc791f-f21c-4984-816e-fe14956104ea.png">

**Comment by EvaaLaw** [comment]
## [IN PROGRESS - to display product image]
<img width="1656" alt="Screenshot 2022-09-07 at 10 59 01 AM" src="https://user-images.githubusercontent.com/57204874/188778896-c9e486f7-69e0-4439-a03c-42142e3ae0cd.png">
