### ISSUE TITLE
Image not showing in popup

### ISSUE THREAD

**Issue by paragasu** [phisoft/enersun-web#26]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/27353/188819579-448fab3c-514f-4039-b035-02c792461475.png">

**Comment by EvaaLaw** [comment]
<img width="1680" alt="Screenshot 2022-09-08 at 3 30 19 PM" src="https://user-images.githubusercontent.com/57204874/189062020-2c5ba8db-1028-4495-8e5d-10a91e5f23c5.png">
