### ISSUE TITLE
Design main banner for enersun website

### ISSUE THREAD

**Issue by paragasu** [phisoft/enersun-web#28]
![Image](https://user-images.githubusercontent.com/27353/193188481-9cf750d7-5ea2-4e09-a519-1a1120071169.png)

![Image](https://user-images.githubusercontent.com/27353/193188754-1da1c729-1a89-4d16-aaf7-bde3ff03d2f8.jpg)

**Comment by lalgal** [comment]
![Mockup Sample - Enersun](https://user-images.githubusercontent.com/112998668/193230681-397646e8-1081-47b8-b795-e78d62f5fb8d.jpg)

**Comment by lalgal** [comment]
[Enersun Main Banner Design.zip](https://github.com/phisoft/enersun-web/files/9682444/Enersun.Main.Banner.Design.zip)

**Comment by paragasu** [comment]
@rosclaritha kamu boleh
