### ISSUE TITLE
Fetch description from api

### ISSUE THREAD

**Issue by paragasu** [phisoft/enersun-web#36]
![image_2022-10-03_11-23-37](https://user-images.githubusercontent.com/27353/193502446-765d1b34-27bf-45f5-bd59-4e566e111435.png)

**Comment by EvaaLaw** [comment]
<img width="1680" alt="Screenshot 2022-10-03 at 3 50 40 PM" src="https://user-images.githubusercontent.com/57204874/193528460-3d0355f6-e228-4a8f-a0f1-062073681939.png">
