### ISSUE TITLE
Redesign `Our Business Goals`

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/enersun-web#7]
Redesign how the info is being displayed. The number doesn't look very pleasing.
![image](https://user-images.githubusercontent.com/30463117/181182366-78dd000c-c830-4262-a9f3-b531616dff28.png)

**Comment by russel0907** [comment]
## Redesign goals & objectives section
![Screenshot (408)](https://user-images.githubusercontent.com/94702093/181412680-bf144a7b-3ef9-4be3-89d9-56073a255c5a.png)

**Comment by russel0907** [comment]
@rosclaritha 

## Design 1
![Screenshot 2022-07-28 at 11-43-29 Enersun — Save Energy Save Earth Love All Serve All](https://user-images.githubusercontent.com/94702093/181431775-899cd96a-9e9f-4cb5-9208-9e84fae472e0.png)

## Design 2
![Enersun-—-Save-Energy-Save-Earth-Love-All-Serve-ll](https://user-images.githubusercontent.com/94702093/181431801-677cb700-7a38-4209-a501-ea1013fb703d.png)

## Design 3
![Enersun-—-Save-Energy-Save-Earth-Love-All-Serve-All](https://user-images.githubusercontent.com/94702093/181431824-4e64b832-73a9-4f0e-818e-3310a1fe4bf3.png)

**Comment by rosclaritha** [comment]
@russel0907 
- [ ] Make the box inline 
- [ ] Change the roman numeral to icons

<img width="1580" alt="Screenshot 2022-08-01 at 10 30 21 AM" src="https://user-images.githubusercontent.com/30463117/182060951-f15fa2dc-a4ba-444f-b379-894002b67fbd.png">

**Comment by russel0907** [comment]
## Business goals & objectives section
![Screenshot 2022-08-01 at 12-09-05 Enersun — Save Energy Save Earth Love All Serve All](https://user-images.githubusercontent.com/94702093/182070572-3b3bbae1-3b73-4d73-a1b9-5a3d62bfa35a.png)
